version: "2.1"
services:
  postgres:
    image: postgres:9.6-alpine
    container_name: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=netguru
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    restart: always

  postgres-test:
    image: postgres:9.6-alpine
    container_name: postgres-test
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=netguru
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - postgres_test_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: always

volumes:
  postgres_data:
  postgres_test_data:
